### ISSUE TITLE
which awesomewm version is being traced?

### ISSUE THREAD

**Issue by haolian9** [kosorin/awesome-code-doc#6]
wow, that's a QoL addition for writing awesomewm related code, awesome!

I think it'd be better to explictly document out which awesomewm version is being traced by this repository.

with that, we can keep the documents up-to-date easier, by using something like `git diff 4.0..4.3`.
and users may use different versions of awesomewm, using documents for wrong version may hurt.

**Comment by haolian9** [comment]
i noticed that awesomewm 4.3 is released at 2019 which is 4 years old, i belive that's the version.

**Comment by kosorin** [comment]
It is attempting to stay up to date with the latest git commit in the awesomewm repository.

**Comment by haolian9** [comment]
thanks for your reply!

though as a new and average awesome user, i'd stay with the latest stable version of awesomewm which is 4.3 right now. and during writing rc.lua i have already added some annotations for modules like awesome, beautiful, naughty, root according to the document of v4.3, that means i should fork this repo and keep them in my own fork, it's a pitty to me. anyway, big thanks to you!

**Comment by kosorin** [comment]
As you noted, 4.3 is 4 years old and many changes have been made since then. Everyone I know is using the latest git version, except you :) .  I recommend it too.

**Comment by haolian9** [comment]
lol, i just began to use awesome, so i really did not know that few users are using v4.3. maybe i'd try to build it from source on master branch.
